# Copyright (c) 2020 vargaconsulting, Toronto,ON Canada
# Author: Varga, Steven <steven@vargaconsulting.ca>

ver-1:
	g++ -std=c++17 variant.cpp -o test

ver-2:
	clang++ -std=c++17 variant.cpp -o test

ver-3:
	clang++ -std=c++17 -stdlib=libc++ variant.cpp -o test


